### ISSUE TITLE
modal

### ISSUE THREAD

**Issue by azeezadio** [hilory16/ebidhaa-quiz#1]
no modal

**Comment by hilory16** [comment]
Yeahhh, I just got on the test yesterday evening so I couldn't finish that up, my Gmail notification was disabled so I wasn't notified. If I can get an hour or less, I'll push that.

**Comment by azeezadio** [comment]
> Yeahhh, I just got on the test yesterday evening so I couldn't finish that up, my Gmail notification was disabled so I wasn't notified. If I can get an hour or less, I'll push that.

ok

**Comment by hilory16** [comment]
Thanks for the patience, I've pushed the code. By the way, the design has been taken off but luckily I had a screenshot, therefore my dimension might not be pixel perfect, I had to use intuition.

**Comment by hilory16** [comment]
> Thanks for the patience, I've pushed the code. By the way, the design has been taken off but luckily I had a screenshot, therefore my dimension might not be pixel perfect, I had to use intuition.

I've also updated the netlify link.
